### ISSUE TITLE
IllegalArgumentException: unexpected url: /api/v1/users/me/presence

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-mobile#1052]
This exception seems pretty common; it seems like we're somehow passing in a relative URL?

https://sentry.io/zulip/zulip-mobile/issues/319501790/

```
IllegalArgumentException: unexpected url: /api/v1/users/me/presence
    at okhttp3.Request$Builder.url(Request.java:142)
    at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:171)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
...
(7 additional frame(s) were not displayed)

unexpected url: /api/v1/users/me/presence
```

**Comment by borisyankov** [comment]
We had an issue in a previous Beta, that we did a faulty check for the realm format, did not append the `https://` and allowed white-space, which caused several issues to be reported. This is likely related.

**Comment by borisyankov** [comment]
I think it is fixed now.

**Comment by borisyankov** [comment]
Reopening, as it is happening again. 
My guess will be that `focusPing` is being called when logged out, thus `realm` is `''`
