### ISSUE TITLE
Crash in AnchorScrollView from Android (7.1.1) 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-mobile#1267]
```
10-07 17:23:56.150 12526-12526/com.zulipmobile E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.zulipmobile, PID: 12526
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                     at com.zulipmobile.AnchorScrollView.findAnchorView(AnchorScrollView.java:227)
                                                                     at com.zulipmobile.AnchorScrollView$2.onScrollChanged(AnchorScrollView.java:156)
                                                                     at android.view.ViewTreeObserver.dispatchOnScrollChanged(ViewTreeObserver.java:1016)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2729)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2641)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2248)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6451)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:943)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:755)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:690)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:929)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-07 17:23:56.150 12526-12526/com.zulipmobile D/AppTracker: App Event: crash
10-07 17:23:56.157 12526-12526/com.zulipmobile I/Process: Sending signal. PID: 12526 SIG: 9

```

To reproduce: after switching narrow while the messages are being loaded and I guess about to be rendered this crashes some times 
Not sure about the exact reason though
And on the current master 6dbb58746d65df2633236d392dff6904be030eeb

**Comment by borisyankov** [comment]
How often does this happen? We better fix it.

**Comment by kunall17** [comment]
1 out of 7-8 times maybe, mostly it was on narrowing
This is also in sentry https://sentry.io/zulip/zulip-mobile/issues/363450265/

**Comment by borisyankov** [comment]
Not sure, pinging @vishwesh3 as he did some changes to the Java side. Maybe related or is a general bug in ScrollView?

**Comment by vishwesh3** [comment]
Sure! will look into it.

**Comment by borisyankov** [comment]
@kunall17 confirm the commit by @vishwesh3 fixes this.

**Comment by kunall17** [comment]
Yup tested for some good 5 minutes no crashes, just the only problem is that log statement will cause a little performance slowdown as the frequency is very fast it generated 8400 statements From 21:46:21.704 to 21:49:29.387 (nearly 3 mins), do comment out the statements when you're doing a release & update in the master as well! 
[logs.txt](https://github.com/zulip/zulip-mobile/files/1367019/logs.txt)

**Comment by borisyankov** [comment]
I don't see any point in logging anything?

**Comment by kunall17** [comment]
Yup we should remove the log statement!
