### ISSUE TITLE
yarn install error:detox: Command failed. Exit code: 65,and yarn ios error

### ISSUE THREAD

**Issue by xiaomingplus** [zulip/zulip-mobile#3107]
Hello,the master branch,run ```yarn install`` failed.

node:v8.12.0
yarn :1.10.1

```bash
 yarn install
yarn install v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-intl@2.4.0" has unmet peer dependency "prop-types@^15.5.4".
[4/4] 📃  Building fresh packages...
[-/3] ⠈ waiting...
[2/3] ⠈ @sentry/cli
error /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/node_modules/detox: Command failed.
Exit code: 65
Command: scripts/postinstall.sh
Arguments:
Directory: /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/node_modules/detox
Output:
/Users/mintvivid/Library/Detox/ios/f09d03bc547fdab9fe6559dff6ddb8d755bfe68d was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/mintvivid/Library/Detox/ios/f09d03bc547fdab9fe6559dff6ddb8d755bfe68d and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from ./ios_src...
info Visit https://yarnpkg.com/en/docs/cli
```

then ,run ```yarn ios```,still failed:

```bash
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/mintvivid/xiaomingplus/inbox/zulip-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/ZulipMobile.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ZulipMobile.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ZulipMobile.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at Promise.then (/Users/mintvivid/xiaomingplus/inbox/zulip-mobile/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

anyone know how to fix it?

**Comment by jainkuniya** [comment]
hi @xiaomingplus Are you able to build `src/ios` project in Xcode?
What are your env version? Xcode, yarn, npm etc

**Comment by xiaomingplus** [comment]
Xcode: 10.1
yarn :1.10.1
npm: '5.10.0'
node:v8.12.0

Xcode also can't build.
