### ISSUE TITLE
Data Migration Management Error - NAV 2015 to Business Central Cloud Upgrade

### ISSUE THREAD

**Issue by RaviThakkarNAV** [zulip/zulip-mobile#3722]
After setting up Data Migration Setup using Self Hosted Microsoft Runtime, got some warnings as shown below and also the questions : 
1) As there is a limitation of data size at a time is 150 GB, does the LDF file is also considered in the database size while migration ?
2) How can we see the progress of syncing and it if it is really getting synced or not ?
3) What the warnings below says from the event viewer ?

WARNING-1------------
'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Unable to create Azure Blob container. Endpoint: https://mseusbchybridrepstg.blob.core.windows.net/, Container Name: msft1a6720t14219984.,Source=Microsoft.DataTransfer.ClientLibrary,StackTrace=   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container)
   at Microsoft.DataTransfer.Runtime.AzureBlobMultipartSink.CreateContainerIfNotExists(),''Type=Microsoft.WindowsAzure.Storage.StorageException,Message=The remote server returned an error: (403) Forbidden.,Source=Microsoft.WindowsAzure.Storage,StorageExtendedMessage=This request is not authorized to perform this operation.
RequestId:3ccca048-401e-0109-7cdc-af2b80000000
Time:2019-12-11T04:38:04.1841415Z,,StackTrace=   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container),''Type=System.Net.WebException,Message=The remote server returned an error: (403) Forbidden.,Source=System,StackTrace=   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext),'
Job ID: 87c3c5bd-ee68-4b20-a09e-785b9ce3e508
Log ID: Warning

WARNING-2------------
DEBUG:
TraceComponentId: TransferClientLibrary
TraceMessageId: StorageSinkCreationBySasException
@logId: Warning
jobId: 87c3c5bd-ee68-4b20-a09e-785b9ce3e508
activityId: 88d39c86-4097-45d3-813b-c586f031ceb9
eventId: StorageSinkCreationBySasException
message: 'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Unable to create Azure Blob container. Endpoint: https://mseusbchybridrepstg.blob.core.windows.net/, Container Name: msft1a6720t14219984.,Source=Microsoft.DataTransfer.ClientLibrary,StackTrace=   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container)
   at Microsoft.DataTransfer.Runtime.AzureBlobMultipartSink.CreateContainerIfNotExists(),''Type=Microsoft.WindowsAzure.Storage.StorageException,Message=The remote server returned an error: (403) Forbidden.,Source=Microsoft.WindowsAzure.Storage,StorageExtendedMessage=This request is not authorized to perform this operation.
RequestId:3ccca048-401e-0109-7cdc-af2b80000000
Time:2019-12-11T04:38:04.1841415Z,,StackTrace=   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container),''Type=System.Net.WebException,Message=The remote server returned an error: (403) Forbidden.,Source=System,StackTrace=   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext),'

WARNING-3------------
'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Unable to create Azure Blob container. Endpoint: https://mseusbchybridrepstg.blob.core.windows.net/, Container Name: msft1a6720t14219984.,Source=Microsoft.DataTransfer.ClientLibrary,StackTrace=   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container)
   at Microsoft.DataTransfer.Runtime.AzureBlobMultipartSink.CreateContainerIfNotExists(),''Type=Microsoft.WindowsAzure.Storage.StorageException,Message=The remote server returned an error: (403) Forbidden.,Source=Microsoft.WindowsAzure.Storage,StorageExtendedMessage=This request is not authorized to perform this operation.
RequestId:3dfe3c63-c01e-009e-73dc-af8380000000
Time:2019-12-11T04:38:04.4876471Z,,StackTrace=   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container),''Type=System.Net.WebException,Message=The remote server returned an error: (403) Forbidden.,Source=System,StackTrace=   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext),'
Job ID: 87c3c5bd-ee68-4b20-a09e-785b9ce3e508
Log ID: Warning

WARNING-4------------

DEBUG:
TraceComponentId: TransferClientLibrary
TraceMessageId: StorageSinkCreationBySasException
@logId: Warning
jobId: 87c3c5bd-ee68-4b20-a09e-785b9ce3e508
activityId: 88d39c86-4097-45d3-813b-c586f031ceb9
eventId: StorageSinkCreationBySasException
message: 'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Unable to create Azure Blob container. Endpoint: https://mseusbchybridrepstg.blob.core.windows.net/, Container Name: msft1a6720t14219984.,Source=Microsoft.DataTransfer.ClientLibrary,StackTrace=   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container)
   at Microsoft.DataTransfer.Runtime.AzureBlobMultipartSink.CreateContainerIfNotExists(),''Type=Microsoft.WindowsAzure.Storage.StorageException,Message=The remote server returned an error: (403) Forbidden.,Source=Microsoft.WindowsAzure.Storage,StorageExtendedMessage=This request is not authorized to perform this operation.
RequestId:3dfe3c63-c01e-009e-73dc-af8380000000
Time:2019-12-11T04:38:04.4876471Z,,StackTrace=   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.DataTransfer.ClientLibrary.AzureStorageExtensions.SafelyCreateIfNotExists(CloudBlobContainer container),''Type=System.Net.WebException,Message=The remote server returned an error: (403) Forbidden.,Source=System,StackTrace=   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext),'

**Comment by gnprice** [comment]
This question doesn't appear to have anything to do with Zulip.
