### ISSUE TITLE
[debug build] App crashes after entering realm url

### ISSUE THREAD

**Issue by jainkuniya** [zulip/zulip-mobile#3863]
Logs:
```
2020-02-02 21:25:54.550 4777-4893/com.zulipmobile.debug W/System.err: me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
2020-02-02 21:25:54.550 4777-4893/com.zulipmobile.debug W/System.err:     at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:99)
2020-02-02 21:25:54.550 4777-4893/com.zulipmobile.debug W/System.err:     at me.leolin.shortcutbadger.ShortcutBadger.removeCountOrThrow(ShortcutBadger.java:119)
2020-02-02 21:25:54.550 4777-4893/com.zulipmobile.debug W/System.err:     at com.zulipmobile.notifications.BadgeCountUpdaterModule.removeCount(BadgeCountUpdaterModule.java:34)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at com.zulipmobile.notifications.BadgeCountUpdaterModule.setBadgeCount(BadgeCountUpdaterModule.java:25)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at android.os.Looper.loop(Looper.java:193)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err: Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at me.leolin.shortcutbadger.impl.DefaultBadger.executeBadge(DefaultBadger.java:32)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err:     at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:97)
2020-02-02 21:25:54.551 4777-4893/com.zulipmobile.debug W/System.err: 	... 13 more
2020-02-02 21:25:54.729 4777-4875/com.zulipmobile.debug D/EGL_emulation: eglMakeCurrent: 0xd676d0a0: ver 3 0 (tinfo 0xd7311030)
```

- I am able to reproduce it on current master 31b6af38, by just uninstalling /cleaning app storage and re-installing app from command line or Android studio.

- Not able to reproduce it on release build, downloaded from play store `26.21.144`

**Comment by jainkuniya** [comment]
Tried to run app on `26.21.144` locally, but still reproducible. So I guess something is wrong with debug build.

**Comment by jainkuniya** [comment]
There is one more exception just above ^ this one

```
2020-02-02 21:31:48.453 5257-5372/com.zulipmobile.debug E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.zulipmobile.debug, PID: 5257
    java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.java:123)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.java:85)
        at okhttp3.Cookie.parse(Cookie.java:311)
        at okhttp3.Cookie.parse(Cookie.java:219)
        at okhttp3.Cookie.parseAll(Cookie.java:445)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:315)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ray-kraesig** [comment]
Uninstalling the debug app and running `react-native run-android` fails to reproduce, for me, on an emulated Nexus 4 (API 21) without Google Play Services.

What device or setup are you installing onto?

**Comment by jainkuniya** [comment]
I tested on multiple devices:
- One plus six physical device running Android 10
- Nexus One API 27 emulator
- Pixel 2 API 28 emulator

**Comment by gnprice** [comment]
One step that might help debug: the error message says
> Unable to load publicsuffixes.gz resource from the classpath.

Do you have that file inside the APK? Here it is in the debug APK I have lying around from my last build:
```
$ unzip -l android/app/build/outputs/apk/debug/app-debug.apk | grep publicsuffixes
    34000  1980-00-00 00:00   okhttp3/internal/publicsuffix/publicsuffixes.gz
```

What does that command show for you (when the bug reproduces?)

**Comment by jainkuniya** [comment]
This got fixed, don't know the root cause. 

Once I added ` multiDexEnabled true` and ran. I am not able to reproduce it.
```
diff --cc android/app/build.gradle
index 25c6e5b2,25c6e5b2..299a9d14
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@@ -122,6 -122,6 +122,7 @@@ android
          targetSdkVersion rootProject.ext.targetSdkVersion
          versionCode 145
          versionName "26.22.145"
++        multiDexEnabled true
      }
      compileOptions {
          sourceCompatibility JavaVersion.VERSION_1_8
```

Now even after removing this line, it is working. 

I got this work around from https://stackoverflow.com/questions/51720114/strange-error-with-glide-while-loading-image-on-production-build

I guess we can close this now, will reopen it in case I face this issue again
