### ISSUE TITLE
Missing dependancy @react-native-community/toolbar-android

### ISSUE THREAD

**Issue by aryanshridhar** [zulip/zulip-mobile#4231]
Hi all , 
Looks like <code>@react-native-community/toolbar-android</code> is missing in the dependencies listed in <code><a href = 'https://github.com/zulip/zulip-mobile/blob/master/package.json'>package.json</a></code> .

When executed <code>react-native start</code> after building by using <code>npx react-native run-android</code> , It throws an error as 
<pre>

error: bundling failed: Error: Unable to resolve module `@react-native-community/toolbar-android` from `node_modules/react-native-vector-icons/lib/toolbar-android.js`: @react-native-community/toolbar-android could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/aryanshridhar/Desktop/zulip-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

</pre>

P.S : It works totally fine after installing <code>@react-native-community/toolbar-android</code> . Let me know if you want a Pr for it !

**Comment by chrisbobbe** [comment]
Interesting! From some searching and reading documentation, it looks like this is something we should do if we want to use something called `ToolbarAndroid`: https://github.com/oblador/react-native-vector-icons/blob/v7.1.0/README.md#toolbarandroid

Are you thinking of starting to use that?
