### ISSUE TITLE
F-Droid Installation: App crashes / doesn't start

### ISSUE THREAD

**Issue by flauschzelle** [zulip/zulip-mobile#5626]
I just installed the Zulip app on my Android phone (Samsung Galaxy S10e, running up-to-date Android 12, installed Zulip via F-Droid) and when I tried to open it (via the button in F-Droid), I got an error message saying it is being stopped repeatedly:

_(My phone's language is set to german, sorry about that. If you need an english translation of anything in the screenshots, please ask me)_

![screenshot showing the error message](https://user-images.githubusercontent.com/44261247/209437748-8bbeaa90-acd0-4ff9-aef7-f2d1ae898b56.jpg)

If I choose 'App-Informationen', I get this info page:

![screenshot of app info screen](https://user-images.githubusercontent.com/44261247/209437761-1ec8b4ac-f261-4404-a51b-dda376d3a663.jpg)

The installation created a shortcut icon on my home screen, but when I click on that, nothing happens except for a short flickering.

The app switcher shows something that seems like zulip is running, but when I try to switch to it, I either get the same error message as above or it just goes to my home screen.

![screenshot of zulip in the app switcher view](https://user-images.githubusercontent.com/44261247/209437769-008b33d0-2c2a-4571-b745-73216d6d4cc2.jpg)

**Comment by flauschzelle** [comment]
Update: I uninstalled it in F-Droid and then tried the apk from the release here instead, and that works fine. So it seems to be an F-Droid specific problem. But still worth fixing, of course!

**Comment by chrisbobbe** [comment]
> tried the apk from the release here instead, and that works fine

Great! I'm glad to hear that our release is working.

I'm happy to leave this issue open for debugging the crash in the F-Droid release, in case someone finds that the fix requires an improvement in our source code.

**Comment by Beanow** [comment]
I've yet to try comparing with the release here, but seeing a crash too.
Logcat tells me it's an SO loading problem.

```
12-28 11:31:19.035  1241  2274 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zulipmobile/.MainActivity bnds=[768,1268][1008,1560]} from uid 10159
12-28 11:31:19.072  1241  1336 I ActivityManager: Start proc 28370:com.zulipmobile/u0a246 for pre-top-activity {com.zulipmobile/com.zulipmobile.MainActivity}
12-28 11:31:19.089  1241  2274 W ActivityTaskManager: Request to remove task ignored for non-existent task 2943
12-28 11:31:19.099 28370 28370 W com.zulipmobil: Insufficient pre-allocated space to mmap vdex.
12-28 11:31:19.122 28370 28370 D Sentry  : io.sentry.auto-init read: false
12-28 11:31:19.122 28370 28370 I Sentry  : Retrieving auto-init from AndroidManifest.xml
12-28 11:31:19.135 28370 28370 D SoLoader: libjscexecutor.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.137 28370 28370 D SoLoader: liblog.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.137 28370 28370 D SoLoader: liblog.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a
12-28 11:31:19.137 28370 28370 D SoLoader: liblog.so found on /system/lib64
12-28 11:31:19.137 28370 28370 D SoLoader: liblog.so loaded implicitly
12-28 11:31:19.137 28370 28370 D SoLoader: libc.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.137 28370 28370 D SoLoader: libc.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a
12-28 11:31:19.137 28370 28370 D SoLoader: libc.so found on /system/lib64
12-28 11:31:19.137 28370 28370 D SoLoader: libc.so loaded implicitly
12-28 11:31:19.137 28370 28370 D SoLoader: libm.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.137 28370 28370 D SoLoader: libm.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a
12-28 11:31:19.138 28370 28370 D SoLoader: libm.so found on /system/lib64
12-28 11:31:19.138 28370 28370 D SoLoader: libm.so loaded implicitly
12-28 11:31:19.138 28370 28370 D SoLoader: libdl.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.138 28370 28370 D SoLoader: libdl.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a
12-28 11:31:19.138 28370 28370 D SoLoader: libdl.so found on /system/lib64
12-28 11:31:19.138 28370 28370 D SoLoader: libdl.so loaded implicitly
12-28 11:31:19.140 28370 28370 W SoLoader: libjscexecutor.so not found on DirectAPKSoSource: 4
12-28 11:31:19.140 28370 28370 W SoLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreactnativeutilsjni.so" not found
12-28 11:31:19.140 28370 28370 W SoLoader: 	at java.lang.Runtime.load0(Runtime.java:938)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at java.lang.System.load(System.java:1631)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.SoLoader$1.load(SoLoader.java:529)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:77)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1038)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:20)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(Unknown Source:0)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:388)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:344)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:33)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.zulipmobile.MainApplication.onCreate(MainApplication.java:66)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.os.Looper.loop(Looper.java:214)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-28 11:31:19.140 28370 28370 W SoLoader: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-28 11:31:19.140 28370 28370 D SoLoader: libjscexecutor.so not found on /system/lib64
12-28 11:31:19.140 28370 28370 D SoLoader: libjscexecutor.so not found on /vendor/lib64
12-28 11:31:19.141 28370 28370 E SoLoader: couldn't find DSO to load: libjscexecutor.so
12-28 11:31:19.141 28370 28370 E SoLoader: 	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64 flags = 0]
12-28 11:31:19.141 28370 28370 E SoLoader: 	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a]
12-28 11:31:19.141 28370 28370 E SoLoader: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
12-28 11:31:19.141 28370 28370 E SoLoader: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
12-28 11:31:19.141 28370 28370 E SoLoader: 	Native lib dir: /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.141 28370 28370 E SoLoader:  result: 0
12-28 11:31:19.142 28370 28370 D SoLoader: libhermes.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.142 28370 28370 D SoLoader: libhermes.so not found on /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a
12-28 11:31:19.142 28370 28370 D SoLoader: libhermes.so not found on /system/lib64
12-28 11:31:19.142 28370 28370 D SoLoader: libhermes.so not found on /vendor/lib64
12-28 11:31:19.142 28370 28370 E SoLoader: couldn't find DSO to load: libhermes.so
12-28 11:31:19.142 28370 28370 E SoLoader: 	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64 flags = 0]
12-28 11:31:19.142 28370 28370 E SoLoader: 	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a]
12-28 11:31:19.142 28370 28370 E SoLoader: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
12-28 11:31:19.142 28370 28370 E SoLoader: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
12-28 11:31:19.142 28370 28370 E SoLoader: 	Native lib dir: /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.142 28370 28370 E SoLoader:  result: 0
12-28 11:31:19.142 28370 28370 D AndroidRuntime: Shutting down VM
12-28 11:31:19.143 28370 28370 E AndroidRuntime: FATAL EXCEPTION: main
12-28 11:31:19.143 28370 28370 E AndroidRuntime: Process: com.zulipmobile, PID: 28370
12-28 11:31:19.143 28370 28370 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64 flags = 0]
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/base.apk!/lib/arm64-v8a]
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	Native lib dir: /data/app/com.zulipmobile-o5FEwOIRoOglg1mRKofKAg==/lib/arm64
12-28 11:31:19.143 28370 28370 E AndroidRuntime:  result: 0
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:25)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:394)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:344)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:33)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.zulipmobile.MainApplication.onCreate(MainApplication.java:66)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-28 11:31:19.143 28370 28370 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-28 11:31:19.144  1241  2274 W ActivityTaskManager:   Force finishing activity com.zulipmobile/.MainActivity
12-28 11:31:19.145  1241 29039 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-28 11:31:19.151 28370 28370 I Process : Sending signal. PID: 28370 SIG: 9
12-28 11:31:19.152  1241 29039 W DropBoxManagerService: Dropping: data_app_crash (2660 > 0 bytes)
12-28 11:31:19.177  1241  1269 I ActivityManager: Process com.zulipmobile (pid 28370) has died: fore TOP 
12-28 11:31:19.178  1241  1337 I libprocessgroup: Successfully killed process cgroup uid 10246 pid 28370 in 0ms
12-28 11:31:19.178   731   731 I Zygote  : Process 28370 exited due to signal 9 (Killed)
12-28 11:31:19.646  1241  1319 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{4387acc u0 com.zulipmobile/.MainActivity t-1 f}
```

**Comment by Beanow** [comment]
Downgrading to `27.196` or older on F-Droid works, so it's a problem with the latest release only.
Note directly downgrading may fail. Instead try uninstalling, then installing the older version.

Installing from https://github.com/zulip/zulip-mobile/releases/tag/v27.197 also works.
There I used `app-arm64-v8a-release.apk`.

**Comment by Beanow** [comment]
So I have a sneaking suspicion it has to do with this:
![image](https://user-images.githubusercontent.com/497556/209800845-28d83d35-7d68-4306-9e5a-de8b1727998a.png)

Not being reflected in this:
https://gitlab.com/fdroid/fdroiddata/-/blob/4eac781f/metadata/com.zulipmobile.yml#L493
```yaml
- yarn add react-native@0.67.5
```

**Comment by licaon-kter** [comment]
Looking now...

**Comment by licaon-kter** [comment]
I was waiting for feedback on https://github.com/zulip/zulip-mobile/issues/5563 so I didn't know RN was updated to 0.68.5

Anyway, can anyone test this apk? https://gitlab.com/fdroid/fdroiddata/-/commit/7c232aa3132dc1eadff32070b165e64a898fc80b#note_1222774587

Right now a new zulip update will be built fine or I'll re-enable this (fixed) version after 2 cycles.

**Comment by Beanow** [comment]
@licaon-kter seems alright with a quick test. Although the changed code signing caused a number of alerts. The app launches and connects as you'd expect.

**Comment by tobbsn** [comment]
is there any update on when this will be available in f-droid?

**Comment by Beanow** [comment]
@tobbsn I think the fix should be applied once a new Zulip app release rolls out.
(i.e. the current release isn't being patched)

Since there's a pre-release https://github.com/zulip/zulip-mobile/releases/tag/v27.198
Hopefully soon :crossed_fingers:

**Comment by licaon-kter** [comment]
Did I forget to enable it? Ooops :)

Anyway next version will come next: https://gitlab.com/fdroid/fdroiddata/-/commit/e0b0e5a1eb92d65aa13bc1c9f904468e2b7631cb#
